### ISSUE TITLE
replica.yml support "sql LIKE" and "sql ILIKE" syntax

### ISSUE THREAD

**Issue by norton120** [Health-Union/snowshu#14]
## Why? 

for a large portion of the SnowShu target audience native python regex is a barrier. But sql “LIKE” and “ILIKE” perl interpretation are second nature. A flag that changes interpretation would be key here. 

## Who Will This Benefit? 

Any developer deep in SQL headspace that is trying to quickly update their replica file without thinking about lookback operators and dot vs star etc.

## How Might You Implement It?

in the base level of the config add this flag:

```
pattern_interpreter: python_regex | sql_like | sql_ilike
```

That sets the way strings are interpreted for the entire replica file. so with `sql_like` set

```
pattern_interpreter: sql_like
source:
  general_relations:
    databases:
    - pattern: '%_PROD' #matches "USERS_PROD" but not 'USERS_prod'
```

‌

```
pattern_interpreter: sql_ilike
source:
  general_relations:
    databases:
    - pattern: '%_PROD' #matches both "USERS_PROD" and 'USERS_prod'
```

‌

```
# no pattern_interpreter set
source:
  general_relations:
    databases:
    - pattern: '%_PROD' #matches neither "USERS_PROD" or 'USERS_prod'
```

‌
