### ISSUE TITLE
Sample Methods => Dict

### ISSUE THREAD

**Issue by norton120** [Health-Union/snowshu#16]
## Why?

right now sample methods are consumed by the config parser as strings, and the needed props are attributes of the sources object. this is gross and wrong and very limiting. 

## Def of Done:

if sample methods were a dict with each of their required attributes passed as params, this would mean:

* params are nicely contained inside the sample method they refer to
* adding relation-level sample methods becomes trivial

## How:

here’s the general idea. Move from 

```
source:
  include_outliers:True
  sample_method: Bernoulli
  probability: 50
```

To:

```
source:
  include_outliers:True
  sample_method:
    bernoulli:
      probability: 50
```

‌
